### ISSUE TITLE
THCudaCheck FAIL file=/pytorch/torch/lib/THC/THCGeneral.c line=844 error=48 : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by fengyuentau** [ChiCheng123/SRN#14]
I got an wired error when trying to run SRN in the docker image I built.
Docker image env:
- use nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 as the base image
- compile py3.6.8 with pip
- install torch 0.3.1, torchvision 0.2.1, numpy 1.16.4, opencv-python 4.1.1.26 through pip
- clone this repo and build extensions following the instructions

Steps to reproduce:
1. Start the image with the following shell script:
    ```shell
    nvidia-docker run --name=srn-$1\
        -it \
	--mount type=bind,source=$WIDERFACE/WIDER_$1/images,target=/root/SRN/data/images \
	--mount type=bind,source=$RESULT/srn/$1,target=/root/SRN/tools/results_dir \
	--mount type=bind,source=$MODELS/srn,target=/root/SRN/model \
	yuentau/srn:torch0.3.1-torchvision0.2.1-py3.6
    ```
2. cd into the $SRN/into directory, replace the `python` in file val.sh by `python3` and then run.

Errors from log:
```shell
# SRN network ...
2019-10-14 04:28:12,105-rk0-load_helper.py#13:restore from ../model/SRN.pth
2019-10-14 04:28:16,853-rk0-load_helper.py#7:remove prefix 'module.'
2019-10-14 04:28:16,969-rk0-test.py#64:build dataloader done
2019-10-14 04:28:16,970-rk0-test.py#74:start validate
THCudaCheck FAIL file=/pytorch/torch/lib/THC/THCGeneral.c line=844 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "test.py", line 118, in validate
    proposals_b = np.vstack((proposals_b, bbox_resize(model(x)['predict'][0].data.cpu().numpy(), resize_scale)))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/SRN/srn/model/srn.py", line 103, in forward
    rpn_pred_ss.append(self.rpn(feature))
  File "/root/SRN/srn/model/resnet_srn.py", line 328, in rpn
    box_feature = self.box_subnet(x)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/SRN/srn/model/resnet_srn.py", line 163, in forward
    out = out + x
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 237, in <module>
    main()
  File "test.py", line 65, in main
    validate(model, cfg, args)
  File "test.py", line 120, in validate
    proposals_b = bbox_resize(model(x)['predict'][0].data.cpu().numpy(), resize_scale)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/SRN/srn/model/srn.py", line 98, in forward
    pyramid_features_fs, pyramid_features_ss = self.feature_extractor(x)
  File "/root/SRN/srn/model/resnet_srn.py", line 288, in feature_extractor
    x = self.conv1(x)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
```

GPU info:
- P100 with 16 gigs gpu RAM

**Comment by fengyuentau** [comment]
Just now I noticed there's a line in the `Evaluation` section from the [readme](https://github.com/ChiCheng123/SRN), which says:
> If the max memory capacity of your GPU is 11G (1080TI) or 12G (TITANXP), please set the max_size in val.sh to 1400. You will get the result: Easy: 96.5, Medium: 95.2, Hard: 89.6.
> If the max memory capacity of your GPU is 24G or larger, please set the max_size in val.sh to 2100. You will get the result: Easy: 96.5, Medium: 95.3, Hard: 90.2.

I set the size of input to 1400 and now SRN can run without the out-of-memory error, but it still prints the following line, 
```shell
THCudaCheck FAIL file=/pytorch/torch/lib/THC/THCGeneral.c line=844 error=48 : no kernel image is available for execution on the device
```
I don't know whether it will have any impact on the performance.
