### ISSUE TITLE
error

### ISSUE THREAD

**Issue by foralliance** [ChiCheng123/SRN#5]
编译完之后，测试时，报错：

```
jmx@jmx-System-Product-Name:~/SRN/tools$ sh val.sh
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from srn.model.resnet_srn import resnet50
  File "/home/jmx/SRN/srn/model/resnet_srn.py", line 1, in <module>
    from .srn import SRN
  File "/home/jmx/SRN/srn/model/srn.py", line 10, in <module>
    from srn.extensions import nms
  File "/home/jmx/SRN/srn/extensions/__init__.py", line 1, in <module>
    from srn.extensions._nms.pth_nms import pth_nms as nms
  File "/home/jmx/SRN/srn/extensions/_nms/pth_nms.py", line 2, in <module>
    from srn.extensions._nms._ext import nms
  File "/home/jmx/SRN/srn/extensions/_nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/jmx/SRN/srn/extensions/_nms/_ext/nms/_nms.so: undefined symbol: PyInt_FromLong
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from srn.model.resnet_srn import resnet50
  File "/home/jmx/SRN/srn/model/resnet_srn.py", line 1, in <module>
    from .srn import SRN
  File "/home/jmx/SRN/srn/model/srn.py", line 10, in <module>
    from srn.extensions import nms
  File "/home/jmx/SRN/srn/extensions/__init__.py", line 1, in <module>
    from srn.extensions._nms.pth_nms import pth_nms as nms
  File "/home/jmx/SRN/srn/extensions/_nms/pth_nms.py", line 2, in <module>
    from srn.extensions._nms._ext import nms
  File "/home/jmx/SRN/srn/extensions/_nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/jmx/SRN/srn/extensions/_nms/_ext/nms/_nms.so: undefined symbol: PyInt_FromLong
jmx@jmx-System-Product-Name:~/SRN/tools$ 
```

这个错误该如何解决呢？
`ImportError: /home/jmx/SRN/srn/extensions/_nms/_ext/nms/_nms.so: undefined symbol: PyInt_FromLong`

**Comment by ChiCheng123** [comment]
Please try to modify the srn/extensions/_nms/build.sh as follow:
'python build.py' -> 'python3 build.py'

**Comment by foralliance** [comment]
@ChiCheng123 
thanks

**Comment by SuckChen** [comment]
try modify the build.sh, still not working

**Comment by SuckChen** [comment]
> @ChiCheng123
> thanks
try modify the build.sh, still not working  : undefined symbol: __cudaPopCallConfiguration



> Please try to modify the srn/extensions/_nms/build.sh as follow:
> 'python build.py' -> 'python3 build.py'
